// Code generated by github.com/kybin/bakego. DO NOT EDIT.
package main

import (
	"bufio"
	"bytes"
	"encoding/hex"
	"fmt"
	"io/ioutil"
	"os"
	"path/filepath"
)

type BakeGoFile struct {
	fname string
	enc string
	data []byte
}

type BakeGo []BakeGoFile

// Extract extracts all remebered files.
func (b BakeGo) Extract() error {
	for _, s := range b {
		fname := s.fname
		enc := s.enc
		data := s.data
		err := os.MkdirAll(filepath.Dir(fname), 0755)
		if err != nil {
			return err
		}
		f, err := os.Create(fname)
		if err != nil {
			return err
		}
		w := bufio.NewWriter(f)
		decoded := data
		if enc == "hex" {
			d, err := fromHex(data)
			if err != nil {
				return err
			}
			decoded = d
		}
		_, err = w.Write(decoded)
		if err != nil {
			return err
		}
		w.Flush()
	}
	return nil
}

// Ensure checks all the BakeGo files are exist.
// It will return nil if all files are exist or return error.
//
// It does not check the files are modified or not.
func (b BakeGo) Ensure() error {
	for _, s := range b {
		_, err := os.Stat(s.fname)
		if err != nil {
			return err
		}
	}
	return nil
}

// When developing a code, it should always be the same
// between bakego data and the actual file.
// If they are not same, it will error.
func (b BakeGo) Identical() error {
	for _, s := range b {
		src, err := ioutil.ReadFile(s.fname)
		if err != nil {
			return err
		}
		dst := s.data
		if s.enc == "hex" {
			d, err := fromHex(dst)
			if err != nil {
				return err
			}
			dst = d
		}
		if !bytes.Equal(src, dst) {
			return fmt.Errorf("bakego: src and dst is not identical: %s", s.fname)
		}
	}
	return nil
}

// fromHex are twin functions that lives both inside and outside of generated file.
// Outside one is for testing purpose.
//
// Note: if you change this function, change it's twin function too.
func fromHex(data []byte) ([]byte, error) {
	reverted := make([]byte, 0, len(data))
	lines := bytes.Split(data, []byte("\n"))
	for _, src := range lines {
		dst := make([]byte, hex.DecodedLen(len(src)))
		_, err := hex.Decode(dst, src)
		if err != nil {
			return nil, err
		}
		reverted = append(reverted, dst...)
	}
	return reverted, nil
}

var bakego BakeGo = make([]BakeGoFile, 0)

func init() {
	bakego = append(bakego, BakeGoFile{"cert/generate-self-signed-cert.sh", "", []byte(`#!/bin/bash

if [ -z $GOROOT ]; then
	GOROOT="/usr/local/go"
fi

"$GOROOT/bin/go" run "$GOROOT/src/crypto/tls/generate_cert.go" -host="localhost" -ca=true
`)})
	bakego = append(bakego, BakeGoFile{"static/roi.css", "", []byte(`body {
	background-color:#EEEEEE;
	margin: 0;
}

a {
	text-decoration: none;
}

hr {
	border: 0;
	height: 0;
	border-top: 1px solid #CCCCCC;
}

#main {
	padding: 8px;
}
`)})
	bakego = append(bakego, BakeGoFile{"static/thumbnail_blank.png", "hex", []byte(`89504e470d0a1a0a0000000d49484452000000a00000005a0802000000b0a4ca05000000017352474200aece1ce90000000467414d410000b18f0bfc61050000
00097048597300000ec300000ec301c76fa864000000d749444154785eedd1010d00000cc3a03b9ff5fb20c502b7d00ac6158c2b185730ae605cc1b8827105e3
0ac6158c2b185730ae605cc1b8827105e30ac6158c2b185730ae605cc1b8827105e30ac6158c2b185730ae605cc1b8827105e30ac6158c2b185730ae605cc1b8
827105e30ac6158c2b185730ae605cc1b8827105e30ac6158c2b185730ae605cc1b8827105e30ac6158c2b185730ae605cc1b8827105e30ac6158c2b185730ae
605cc1b8827105e30ac6158c2b185730ae605cc1b8827105e30ac6158c2b185730ae605cc1b8827105e30aa66d0f6d3ebc1e37ad5be00000000049454e44ae42
6082
`)})
	bakego = append(bakego, BakeGoFile{"tmpl/index.html", "", []byte(`<!doctype html>
<html>
<head>
	<title>roi</title>
	<link rel="stylesheet" href="/static/roi.css">
</head>
<body style="">
	{{template "nav.html" $}}
</body>
</html>
`)})
	bakego = append(bakego, BakeGoFile{"tmpl/login.html", "", []byte(`<!doctype html>
<html>
<head>
	<title>roi</title>
	<link rel="stylesheet" href="/static/roi.css">
</head>
<body style="background-color:#F0F0F0">
	{{template "nav.html" $}}
	<div style="width:350px;margin:auto;">
		<div style="height:100px;">
		</div>
		<form method="post">
		<div style="width:300px;border:1px solid #666666;border-radius:2px;padding:30px 20px;background-color:white;">
			<div style="margin-bottom:5px;">아이디</div>
			<input id="login_id" name="id" value="" type="text" style="box-sizing:border-box;border:1px solid grey;width:100%;height:35px;padding:0px 10px 2px 10px;font-size:15px;"></input>
			<div style="height:10px;"></div>
			<div style="margin-bottom:5px;">패스워드</div>
			<input id="login_password" name="password" value="" type="password" style="box-sizing:border-box;border:1px solid grey;width:100%;height:35px;padding:0px 10px 2px 10px;font-size:15px;"></input>
			<div style="height:35px;"></div>
			<input type="submit" style="box-sizing:border-box;width:100%;height:40px;display:flex;justify-content:center;align-items:center;background-color:#2FBC35;border:1px solid #16AA16;color:white;font-size:15px;" value="로그인"></div>
		</div>
		</form>
	</div>
</body>
</html>
`)})
	bakego = append(bakego, BakeGoFile{"tmpl/nav.html", "", []byte(`<div style="position:sticky;top:0;width:100%;height:40px;background-color:#48F; display:flex; color:#999;">
	<div style="width:150px; background-color:#37F; display:flex; margin:0px 1px;">
		<div style="color:white; align-self:center; font-size:30px; padding-left:10px;"><a href="/" style="color:white;">ROI</a></div>
	</div>
	<div style="background-color:#37F; width:120px; margin:0px 1px; font-size:20px; display:flex; padding:5px; justify-content:center; align-items:flex-end"><div><a href="/search/" style="color:white;">Search</a></div></div>
	<div style="background-color:#37F; width:120px; margin:0px 1px; font-size:20px; display:flex; padding:5px; justify-content:center; align-items:flex-end"><div><a href="/overview/" style="color:white;">Overview</a></div></div>
	<div style="background-color:#37F; flex-grow:1;"></div>
	<div style="background-color:#37F; display:flex;">
	{{if eq $.LoggedInUser ""}}
		<div style="color:white; align-self:center; font-size:18px; padding-right:15px;"><a href="/login/" style="color:white;">로그인</a> <span style="color:#BBBBBB;font-size:12px;">또는</span> <a href="/signup/" style="color:white;">가입</a></div>
	{{else}}
		<div style="color:white; align-self:center; font-size:18px; padding-right:15px;">
			<a href="/settings/profile" style="color:white;">{{$.LoggedInUser}}</a> <a href="/logout/"><span style="color:white;font-size:12px;">(로그아웃)</span></a>
		</div>
	{{end}}
	</div>
</div>

`)})
	bakego = append(bakego, BakeGoFile{"tmpl/profile.html", "", []byte(`<!doctype html>
<html>
<head>
	<title>roi</title>
	<link rel="stylesheet" href="/static/roi.css">
</head>
<body style="">
	{{template "nav.html" $}}
	<div id="main" style="display:flex">
		<div id="left" style="width:200px;"></div>
		<div id="right" style="display:flex;flex-direction:column;width:500px;">
			<div id="profile-block">
				<div style="font-size:20px;color:#333333;padding:50px 0 20px 0;border-bottom:solid 1px #AAAAAA;">사용자 정보</div>
				<form method="post">
					<div style="margin:20px 0 5px 0;">이름</div>
					<input type="text" name="kor-name" style="width:100%;box-sizing:border-box;" value="{{$.User.KorName}}" />
					<div style="margin:20px 0 5px 0;">영문이름</div>
					<input type="text" name="name" style="width:100%;box-sizing:border-box;" value="{{$.User.Name}}" />
					<div style="margin:20px 0 5px 0;">팀</div>
					<select type="text" name="team" style="width:100%;box-sizing:border-box;">
						<option value="" {{if eq $.User.Team ""}}selected{{end}}>없음</option>
						<option value="mod" {{if eq $.User.Team "mod"}}selected{{end}}>모델링</option>
						<option value="rig" {{if eq $.User.Team "rig"}}selected{{end}}>리깅</option>
						<option value="ani" {{if eq $.User.Team "ani"}}selected{{end}}>애니메이션</option>
						<option value="lit" {{if eq $.User.Team "lit"}}selected{{end}}>라이팅</option>
						<option value="fx" {{if eq $.User.Team "fx"}}selected{{end}}>FX</option>
						<option value="matte" {{if eq $.User.Team "matte"}}selected{{end}}>매트</option>
						<option value="motion" {{if eq $.User.Team "motion"}}selected{{end}}>모션</option>
						<option value="comp" {{if eq $.User.Team "comp"}}selected{{end}}>합성</option>
						<option value="sup" {{if eq $.User.Team "sup"}}selected{{end}}>수퍼바이저</option>
						<option value="pd" {{if eq $.User.Team "pd"}}selected{{end}}>PD</option>
					</select>
					<div style="margin:20px 0 5px 0;">직책</div>
					<select type="text" name="position" style="width:100%;box-sizing:border-box;">
						<option value=""{{if eq $.User.Position ""}}selected{{end}}>없음</option>
						<option value="lead" {{if eq $.User.Position "lead"}}selected{{end}}>팀장</option>
					</select>
					<div style="margin:20px 0 5px 0;">이메일</div>
					<input type="text" name="email" style="width:100%;box-sizing:border-box;" value="{{$.User.Email}}" />
					<div style="margin:20px 0 5px 0;">전화번호</div>
					<input type="text" name="phone-number" style="width:100%;box-sizing:border-box;" value="{{$.User.PhoneNumber}}" />
					<div style="margin:20px 0 5px 0;">입사일</div>
					<input type="text" name="entry-date" style="width:100%;box-sizing:border-box;" value="{{$.User.EntryDate}}" />
					<div style="height:40px;"></div>
					<button type="submit" value="Submit" style="box-sizing:border-box;width:100%;height:40px;background-color:#2FBC35;border:1px solid #16AA16;color:white;font-size:15px;">설정 저장</button>
					<div style="height:40px;"></div>
				</form>
			</div>
			<div id="password-block">
				<div style="font-size:20px;color:#333333;padding:50px 0 20px 0;border-bottom:solid 1px #AAAAAA;">비밀번호 변경</div>
				<form action="/update-password" method="post">
					<div style="margin:20px 0 5px 0;">기존 패스워드</div>
					<input type="password" name="old-password" style="width:100%;box-sizing:border-box;" />
					<div style="margin:20px 0 5px 0;">새 패스워드</div>
					<input type="password" name="new-password" style="width:100%;box-sizing:border-box;" />
					<div style="margin:20px 0 5px 0;">새 패스워드 재입력</div>
					<input type="password" name="new-password-confirm" style="width:100%;box-sizing:border-box;" />
					<div style="height:40px;"></div>
					<button type="submit" value="Submit" style="box-sizing:border-box;width:100%;height:40px;background-color:#2FBC35;border:1px solid #16AA16;color:white;font-size:15px;">비밀번호 변경</button>
					<div style="height:40px;"></div>
				</form>
			</div>
		</div>
	</div>
</body>
</html>
`)})
	bakego = append(bakego, BakeGoFile{"tmpl/search.html", "", []byte(`<!doctype html>
<html>
<head>
	<title>roi</title>
	<script src="/static/vue.js"></script>
	<script>
	function projectChanged() {
		prj = document.getElementById("project-select").value;
		document.location.href = prj;
	}
	</script>
	<link rel="stylesheet" href="/static/roi.css">
</head>
<body style="">
	{{template "nav.html" $}}
	<div style="position:sticky;top:40px;width:100%;height:45px;background-color:#DDDDDD;padding:5px;">
		<div style="display:flex;">
			<select id="project-select" onchange="projectChanged()">
				{{range $.Projects}}
					<option value={{.}} {{if eq . $.Project}}selected{{end}}>{{.}}</option>
				{{end}}
			</select>
			<form>
				<input type="text" name="scene" placeholder="씬" value="{{$.FilterScene}}">
				<input type="text" name="shot" placeholder="샷" value="{{$.FilterShot}}">
				<input type="text" name="tag" placeholder="태그" value="{{$.FilterTag}}">
				<select id="status-select" name="status">
					<option value="" {{if eq $.FilterStatus ""}}selected{{end}}>모든 상태</option>
					<option value="in-progress" {{if eq $.FilterStatus "in-progress"}}selected{{end}}>진행중</option>
					<option value="done" {{if eq $.FilterStatus "done"}}selected{{end}}>완료</option>
				</select>
				<input type="submit" value="검색">
			</form>
		</div>
	</div>
	<div id="main">
		<div style="display:flex;flex:1;">
			<div style="flex:1;">
			{{range .Shots}}
				<div class="shot" style="padding:5px 10px 2px 10px;border:solid 1px #DDDDDD;background-color:white;">
					<div class="shot-head" style="height:20px;display:flex;align-items:end;margin-bottom:3px;font-size:15px;">
						<div style="width:192px;margin-right:20px;">
							<a href="/shot/{{$.Project}}/{{.Name}}" style="color:black;">{{.Name}}</a>
							{{if ne .Scene ""}}
							<div style="font-size:10px;color:#BBBBBB;display:inline-block;"> / {{.Scene}}</div>
							{{end}}
						</div>
						<div style="flex:1;font-size:14px;">{{.CGDescription}}</div>
						<div style="font-size:12px;align-items:end;padding:0 4px;background-color:#4488AA;color:white;">{{.Status}}</div>
					</div>
					<div class="shot-main" style="display:flex;">
						<div style="width:192px;margin-right:20px;">
						{{if hasThumbnail $.Project .Name}}
							<img style="width:192px;height:108px" src="/thumbnail/{{$.Project}}/{{.Name}}.png" />
						{{else}}
							<div style="box-sizing:border-box;width:192px;height:108px;color:#444444;background-color:#BBBBBB;font-size:12px;padding:4px;">{{.Description}}</div>
						{{end}}
						</div>
						<div class="shot-output" style="flex:1;font-size:12px;display:flex;flex-direction:column;margin-right:20px;border-top:solid 1px gray;">
							<div style="display:flex;border-bottom:solid 1px #BBBBBB;margin-top:2px;">
								<div style="width:30px;">1</div><div style="width:100px;">2014-01-01</div><div style="flex:1;">O.K</div>
							</div>
						</div>
					</div>
					<div class="shot-footer" style="display:flex;">
						<div class="shot-timecode" style="width:192px;margin-right:20px;display:flex;justify-content:space-between;font-size:11px;color:gray;">
							<div>{{.TimecodeIn}} - {{.TimecodeOut}}</div><div>{{.Duration}}f</div>
						</div>
						<div style="font-size:11px;color:gray;">
							{{range $i, $v := .Tags -}}
								{{if ne $i 0}}, {{end}}<a href="?tag={{.}}" style="color:gray;">{{.}}</a>
							{{- end}}
						</div>
					</div>
				</div>
				<div style="height:10px;"></div>

			{{end}}
			</div>
		</div>
	</div>
</body>
</html>
`)})
	bakego = append(bakego, BakeGoFile{"tmpl/shot.html", "", []byte(`<!doctype html>
<html>
<head>
	<title>roi</title>
	<link rel="stylesheet" href="/static/roi.css">
	<style>
	</style>
</head>
<body style="">
	{{template "nav.html" $}}
	<div id="main">
		<div style="display:flex;align-items:end;">
			<div style="font-size:30px;">{{$.Shot.Name}}</div>
			<div style="width:20px;"></div>
			<div style="font-size:15px;background-color:#4488AA;margin:5px;padding:1px 4px;border-radius:2px;">{{$.Shot.Status}}</div>
			<div style="font-size:15px;background-color:#44AA66;margin:5px;padding:1px 4px;border-radius:2px;">2018-01-01 (187일 지남)</div>
			<div style="flex:1;"></div>
			<div style="font-size:15px;"><a href="/search/{{$.Project}}" style="color:grey;">{{$.Project}}</a> <span style="color:#444444">/</span> <a href="/search/{{$.Project}}?scene={{$.Shot.Scene}}" style="color:grey;">{{$.Shot.Scene}}</a></div>
		</div>
		<hr>
		<div style="display:flex;">
			<div style="min-width:320px;min-height:180px;background-color:grey;"></div>
			<div style="min-width:20px;"></div>
			<!--
			<div style="flex:2;display:flex;flex-direction:column;">
			</div>
			-->
			<div style="flex:1;display:flex;flex-direction:column;">
				<div style="display:flex;"><div style="min-width:80px;">샷 내용</div><div style="color:grey;min-width:20px;">|</div><div>{{.Shot.Description}}</div></div>
				<div style="display:flex;"><div style="min-width:80px;">CG내용</div><div style="color:grey;min-width:20px;">|</div><div>{{.Shot.CGDescription}}</div></div>
				<div style="flex:1;"></div>
				<div style="display:flex;min-width:150px;"><div style="width:80px;">타임코드</div><div style="color:grey;min-width:20px;">|</div><div style="flex:1;">{{.Shot.TimecodeIn}}-{{.Shot.TimecodeOut}}</div></div>
				<div style="display:flex;min-width:150px;"><div style="width:80px;">프레임</div><div style="color:grey;min-width:20px;">|</div></div>
				<div style="display:flex;min-width:150px;"><div style="width:80px;">스캔경로</div><div style="color:grey;min-width:20px;">|</div></div>
				<div style="display:flex;min-width:150px;"><div style="width:80px;">mov경로</div><div style="color:grey;min-width:20px;">|</div></div>
			</div>
		</div>
		<div style="height:15px;"></div>
		<div style="display:flex;flex-direction:column;height:60px;border:solid 1px #DDDDDD;padding:2px;">
			<div style="flex:1;">
				컨펌
			</div>
			<div style="display:flex;font-size:12px;">
				<div>#8 2018-09-11</div>
				<div style="flex:1;"></div>
				<div>이전 컨펌 내용</div>
			</div>
		</div>
		<div style="height:15px;"></div>
		<!-- <div style="display:flex;flex-wrap:wrap;border:solid;border-width:1px;border-color:#888888;"> -->
		<div style="display:flex;flex-wrap:wrap;border:solid 1px #DDDDDD;background-color:#BBBBBB;">
			<div style="flex:1;min-width:100px;border-right:solid 1px #DDDDDD;padding:2px;"><div style="border-radius:2px;width:6px;background-color:#CCCCCC;padding:2px;"></div><div>Mod</div></div>
			<div style="flex:1;min-width:100px;border-right:solid 1px #DDDDDD;padding:2px;"><div style="border-radius:2px;width:6px;background-color:#FFDD66;padding:2px;"></div><div>Rig</div></div>
			<div style="flex:1;min-width:100px;border-right:solid 1px #DDDDDD;padding:2px;"><div style="border-radius:2px;width:6px;background-color:#44AA44;padding:2px;"></div><div>Ani</div></div>
			<div style="flex:1;min-width:100px;border-right:solid 1px #DDDDDD;padding:2px;"><div style="border-radius:2px;width:6px;background-color:#2266DD;padding:2px;"></div><div>Track</div></div>
			<div style="flex:1;min-width:100px;border-right:solid 1px #DDDDDD;padding:2px;"><div style="border-radius:2px;width:6px;background-color:#BB0022;padding:2px;"></div><div>Light</div></div>
			<div style="flex:1;min-width:100px;border-right:solid 1px #DDDDDD;padding:2px;"><div style="border-radius:2px;width:6px;background-color:#CCCCCC;padding:2px;"></div><div>Fx</div></div>
			<div style="flex:1;min-width:100px;border-right:solid 1px #DDDDDD;padding:2px;"><div style="border-radius:2px;width:6px;background-color:#CCCCCC;padding:2px;"></div><div>Matte</div></div>
			<div style="flex:1;min-width:100px;border-right:solid 1px #DDDDDD;padding:2px;"><div style="border-radius:2px;width:6px;background-color:#CCCCCC;padding:2px;"></div><div>Motion</div></div>
			<div style="flex:1;min-width:100px;border-right:solid 1px #DDDDDD;padding:2px;"><div style="border-radius:2px;width:6px;background-color:#CCCCCC;padding:2px;"></div><div>Comp</div></div>
		</div>
	</div>
</body>
</html>
`)})
	bakego = append(bakego, BakeGoFile{"tmpl/signup.html", "", []byte(`<!doctype html>
<html>
<head>
	<title>roi</title>
	<link rel="stylesheet" href="/static/roi.css">
</head>
<body style="background-color:#F0F0F0">
	{{template "nav.html" $}}
	<div style="width:350px;margin:auto;">
		<div style="height:100px;">
		</div>
		<form method="post">
		<div style="width:300px;border:1px solid #666666;border-radius:2px;padding:30px 20px;background-color:white;">
			<div style="margin-bottom:5px;">아이디</div>
			<input id="signup_id" name="id" value="" type="text" style="box-sizing:border-box;border:1px solid grey;width:100%;height:35px;padding:0px 10px 2px 10px;font-size:15px;"></input>
			<div style="height:10px;"></div>
			<div style="margin-bottom:5px;">패스워드</div>
			<input id="signup_password" name="password" value="" type="password" style="box-sizing:border-box;border:1px solid grey;width:100%;height:35px;padding:0px 10px 2px 10px;font-size:15px;"></input>
			<div style="height:10px;"></div>
			<div style="margin-bottom:5px;">패스워드 재입력</div>
			<input id="signup_password_confirm" name="password_confirm" value="" type="password" style="box-sizing:border-box;border:1px solid grey;width:100%;height:35px;padding:0px 10px 2px 10px;font-size:15px;"></input>
			<div style="height:35px;"></div>
			<input type="submit" style="box-sizing:border-box;width:100%;height:40px;display:flex;justify-content:center;align-items:center;background-color:#DD2233;border:1px solid #CC1122;color:white;font-size:15px;" value="가입하기"></div>
		</div>
		</form>
	</div>
</body>
</html>
`)})
}
