language: go

go:
 - 1.11.x

env:
 - GO111MODULE=on

script:
 - go test -race -coverprofile=coverage.txt -covermode=atomic ./...
 - go vet ./...

after_success:
 - bash <(curl -s https://codecov.io/bash)
